flowchart TD
    A[Inicio] --> B[Clic en módulo eCenter]
    B --> C[Scroll contenedor de aplicaciones]
    C --> D[Clic en 'Visor de informacion tecnica de red']
    D --> E[Clic en botón 'Mostrar filtro']
    E --> F[Clic en <select> del filtro]
    F --> G[Seleccionar opción 'CENTRO POBLADO']
    G --> H[Escribir 'PALMIRA' en campo de texto]
    H --> I[Clic en botón 'Aplicar filtro']
    I --> J[Fin]
