flowchart TD
    A[Inicio] --> B[Clic en módulo eCenter]
    B --> C[Scroll en contenedor de aplicaciones]
    C --> D[Abrir 'Contenido clases de negocio']
    D --> E[Clic en botón picklist]
    E --> F[Seleccionar entidad correspondiente a revisar 'Entidad modelos']
    F --> G[Clic en botón Seleccionar]
    G --> H[Abrir nuevo registro]
    H --> I[Seleccionar Fabricante ID 1 - 'HUAWEI']
    I --> J[Confirmar selección Fabricante]
    J --> K[Diligenciar Nombre 'TEST CREAR']
    K --> L[Diligenciar cantidad de slots 1 a 50]
    L --> M[Seleccionar Tipo ID 21 - 'ELEMENTO TERCIARIO - GADGESTS']
    M --> N[Confirmar selección Tipo]
    N --> O[Diligenciar Descripción]
    O --> P[Seleccionar Ícono]
    P --> Q[Seleccionar Localidad]
    Q --> R[Confirmar Localidad]
    R --> S[Guardar registro]

    S --> T[Clic en barra de búsqueda]
    T --> U[Buscar 'TEST CREAR']
    U --> V[Seleccionar registro con ID mayor]
    V --> W[Validar campo Nombre]

    W --> X[Editar registro]
    X --> Y[Actualizar Fabricante a ID 2 - FIBERHOME]
    Y --> Z[Actualizar Nombre a 'TEST EDITAR']
    Z --> AA[Actualizar slots 51 a 100]
    AA --> AB[Actualizar Tipo a ID 1]
    AB --> AC[Confirmar Tipo]
    AC --> AD[Actualizar Descripción]
    AD --> AE[Guardar edición]
    AE --> AF[Buscar 'TEST EDITAR']
    AF --> AG[Seleccionar registro con ID mayor]
    AG --> AH[Eliminar registro]
    AH --> AI[Fin]
